environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'
    - nodejs_version: '12'

install:
- ps: Install-Product node $env:nodejs_version
- npm install --global yarn@latest
- set PATH=%APPDATA%\npm;%PATH%
- yarn install

matrix:
  fast_finish: true
build: false
shallow_clone: true

test_script:
- node --version
- yarn --version

- cd packages/bladejs
- yarn lint
- yarn build:prod
- yarn test
- cd ../..

- cd packages/bladejs-compiler
- yarn lint
- yarn build:prod
- yarn test
- cd ../..

cache:
- '%APPDATA%\npm-cache'
